
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cw2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Seehope123
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  security:
    user:
      name: admin
      password: 123456